# Generated by Django 4.2.11 on 2025-09-23 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("promgen", "0036_farm_project_alter_project_farm"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="farm",
        ),
        migrations.AlterField(
            model_name="farm",
            name="project",
            field=models.OneToOneField(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="promgen.project"
            ),
        ),
    ]
